version: "3.5"
services:
  kafka:
    image: 'confluentinc/cp-kafka:7.5.3'
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://kafka:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 32
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_ROLL_HOURS: 24
      KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
      # SASL disabled for local example
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      KAFKA_SUPER_USERS: "User:admin"
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  client:
    build:
      context: ..
      dockerfile: example/client.dockerfile
    volumes:
      - ..:/app
    depends_on:
      - kafka
      - redis

  server:
    build:
      context: ..
      dockerfile: example/server.dockerfile
    volumes:
      - ..:/app
    depends_on:
      - kafka
      - redis

  futures-consumer:
    build:
      context: ..
      dockerfile: example/futures-consumer.dockerfile
    volumes:
      - ..:/app
    depends_on:
      - redis

  futures-publisher:
    build:
      context: ..
      dockerfile: example/futures-publisher.dockerfile
    volumes:
      - ..:/app
    depends_on:
      - redis

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

#networks:
#  car2-network:
#    external: true
